# Generated by Django 3.2.5 on 2022-02-28 01:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Traffic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_id', models.IntegerField(default=-1)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('delete_time', models.DateTimeField(null=True)),
            ],
        ),
    ]
