# Generated by Django 3.2.12 on 2022-03-19 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detectme', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('all_count', models.IntegerField(default=-1)),
                ('time_1', models.IntegerField(default=0)),
                ('time_2', models.IntegerField(default=0)),
                ('time_3', models.IntegerField(default=0)),
                ('time_4', models.IntegerField(default=0)),
                ('time_5', models.IntegerField(default=0)),
                ('time_6', models.IntegerField(default=0)),
                ('time_7', models.IntegerField(default=0)),
                ('time_8', models.IntegerField(default=0)),
                ('time_9', models.IntegerField(default=0)),
                ('time_10', models.IntegerField(default=0)),
                ('time_11', models.IntegerField(default=0)),
                ('time_12', models.IntegerField(default=0)),
                ('time_13', models.IntegerField(default=0)),
                ('time_14', models.IntegerField(default=0)),
                ('time_15', models.IntegerField(default=0)),
                ('time_16', models.IntegerField(default=0)),
                ('time_17', models.IntegerField(default=0)),
                ('time_18', models.IntegerField(default=0)),
                ('time_19', models.IntegerField(default=0)),
                ('time_20', models.IntegerField(default=0)),
                ('time_21', models.IntegerField(default=0)),
                ('time_22', models.IntegerField(default=0)),
                ('time_23', models.IntegerField(default=0)),
                ('time_24', models.IntegerField(default=0)),
                ('count_date', models.DateField()),
            ],
        ),
    ]
