# Generated by Django 3.2.5 on 2022-05-04 02:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detectme', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='count_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 4, 2, 6, 6, 221475)),
        ),
        migrations.AlterField(
            model_name='todayrecord',
            name='count_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 4, 2, 6, 6, 220475)),
        ),
    ]
