# Generated by Django 3.2.5 on 2022-04-13 21:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detectme', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traffic',
            name='id',
        ),
        migrations.AlterField(
            model_name='record',
            name='count_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 13, 21, 44, 57, 554189)),
        ),
        migrations.AlterField(
            model_name='traffic',
            name='person_id',
            field=models.IntegerField(default=-1, primary_key=True, serialize=False),
        ),
    ]
