# Generated by Django 3.2.5 on 2022-04-13 22:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detectme', '0002_auto_20220413_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='count_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 13, 22, 19, 59, 200342)),
        ),
    ]
