# Generated by Django 3.2.12 on 2022-03-19 09:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('detectme', '0002_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='count_date',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='time_1',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='time_10',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='time_11',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='time_12',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='time_13',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='time_14',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='time_15',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='time_16',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='time_17',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='time_18',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='time_19',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='time_2',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='time_20',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='time_21',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='time_22',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='time_23',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='time_24',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='time_3',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='time_4',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='time_5',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='time_6',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='time_7',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='time_8',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='time_9',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
