# Generated by Django 3.2.12 on 2022-03-19 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detectme', '0003_auto_20220319_1836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='all_count',
        ),
    ]
