# Generated by Django 3.2.12 on 2022-03-20 06:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('detectme', '0004_remove_record_all_count'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Record',
        ),
        migrations.RemoveField(
            model_name='traffic',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='traffic',
            name='delete_time',
        ),
        migrations.AddField(
            model_name='traffic',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='traffic',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
