# Generated by Django 4.0.4 on 2022-05-16 22:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detectme', '0005_auto_20220504_0244'),
    ]

    operations = [
        migrations.CreateModel(
            name='line_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.IntegerField()),
                ('line_one_x', models.IntegerField()),
                ('line_one_y', models.IntegerField()),
                ('line_two_x', models.IntegerField()),
                ('line_two_y', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='record',
            name='count_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 16, 22, 15, 15, 992057), null=True),
        ),
        migrations.AlterField(
            model_name='todayrecord',
            name='count_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 16, 22, 15, 15, 991059)),
        ),
    ]
