# Generated by Django 4.0.4 on 2022-05-18 14:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detectme', '0005_auto_20220504_0244'),
    ]

    operations = [
        migrations.CreateModel(
            name='lineRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_id', models.IntegerField()),
                ('people_count', models.IntegerField(default=0, null=True)),
                ('cross_time', models.DateTimeField(default=datetime.datetime(2022, 5, 18, 14, 20, 39, 616704), null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='record',
            name='count_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 18, 14, 20, 39, 617734), null=True),
        ),
        migrations.AlterField(
            model_name='todayrecord',
            name='count_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 18, 14, 20, 39, 617734)),
        ),
    ]
