# Generated by Django 3.2.12 on 2022-03-20 07:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detectme', '0005_auto_20220320_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traffic',
            name='date',
            field=models.DateField(default=datetime.date(2022, 3, 20)),
        ),
        migrations.AlterField(
            model_name='traffic',
            name='time',
            field=models.TimeField(default=datetime.time(16, 0, 29, 352088)),
        ),
    ]
