# Generated by Django 4.0.4 on 2022-05-17 10:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detectme', '0006_line_list_alter_record_count_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='count_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 17, 10, 27, 31, 78097), null=True),
        ),
        migrations.AlterField(
            model_name='todayrecord',
            name='count_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 17, 10, 27, 31, 77103)),
        ),
    ]
