# Generated by Django 3.2.12 on 2022-03-20 07:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detectme', '0007_alter_traffic_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traffic',
            name='time',
            field=models.DateTimeField(default=datetime.time(16, 29, 21, 709779)),
        ),
    ]
