# Generated by Django 3.2.5 on 2022-04-13 23:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detectme', '0008_alter_record_count_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='count_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 13, 23, 39, 46, 517130)),
        ),
    ]
