# Generated by Django 3.2.12 on 2022-03-20 07:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('detectme', '0008_alter_traffic_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traffic',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 3, 20, 7, 31, 56, 647112, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='traffic',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 20, 7, 31, 56, 647112, tzinfo=utc)),
        ),
    ]
