# Generated by Django 3.2.12 on 2022-03-20 07:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('detectme', '0009_auto_20220320_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traffic',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='traffic',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
