# Generated by Django 4.0.3 on 2022-03-22 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detectme', '0016_alter_traffic_date_alter_traffic_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traffic',
            name='time',
            field=models.TimeField(),
        ),
    ]
