# Generated by Django 4.0.3 on 2022-03-22 04:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('detectme', '0017_alter_traffic_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_1', models.IntegerField(default=0, null=True)),
                ('time_2', models.IntegerField(default=0, null=True)),
                ('time_3', models.IntegerField(default=0, null=True)),
                ('time_4', models.IntegerField(default=0, null=True)),
                ('time_5', models.IntegerField(default=0, null=True)),
                ('time_6', models.IntegerField(default=0, null=True)),
                ('time_7', models.IntegerField(default=0, null=True)),
                ('time_8', models.IntegerField(default=0, null=True)),
                ('time_9', models.IntegerField(default=0, null=True)),
                ('time_10', models.IntegerField(default=0, null=True)),
                ('time_11', models.IntegerField(default=0, null=True)),
                ('time_12', models.IntegerField(default=0, null=True)),
                ('time_13', models.IntegerField(default=0, null=True)),
                ('time_14', models.IntegerField(default=0, null=True)),
                ('time_15', models.IntegerField(default=0, null=True)),
                ('time_16', models.IntegerField(default=0, null=True)),
                ('time_17', models.IntegerField(default=0, null=True)),
                ('time_18', models.IntegerField(default=0, null=True)),
                ('time_19', models.IntegerField(default=0, null=True)),
                ('time_20', models.IntegerField(default=0, null=True)),
                ('time_21', models.IntegerField(default=0, null=True)),
                ('time_22', models.IntegerField(default=0, null=True)),
                ('time_23', models.IntegerField(default=0, null=True)),
                ('time_24', models.IntegerField(default=0, null=True)),
                ('count_date', models.DateField(default=django.utils.timezone.now, null=True)),
            ],
        ),
    ]
