# Generated by Django 4.0.3 on 2022-03-22 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detectme', '0018_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='all_count',
            field=models.IntegerField(default=0),
        ),
    ]
