# Generated by Django 4.0.3 on 2022-03-22 04:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('detectme', '0019_record_all_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='count_date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
