# Generated by Django 4.0.3 on 2022-03-22 04:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('detectme', '0020_alter_record_count_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='count_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 22, 4, 39, 57, 272445, tzinfo=utc)),
        ),
    ]
